# SConstruct — Build script for Snapshot Pack Creator
#
# Targets (in order):
#   1. Patch src/_version.py with the current build timestamp
#   2. Convert umbrella AsciiDoc files to PDF  (requires asciidoctor-pdf)
#   3. Freeze the application with PyInstaller  (one-directory bundle)
#   4. Copy PDFs into the frozen bundle
#   5. Pack everything into a console SFX installer  (7zCon.sfx, no UAC)
#
# Prerequisites
# -------------
#   1. Run cli.bat to create the venv and install pip requirements.
#   2. Install asciidoctor-pdf (Ruby gem):
#        gem install asciidoctor-pdf
#   3. Install 7-Zip Extra and place 7zCon.sfx beside 7z.exe or in tools/.
#        https://www.7-zip.org/download.html  ("7-Zip Extra")
#   4. Install PyInstaller into the venv:
#        venv\Scripts\pip install pyinstaller
#
# Usage
# -----
#   scons            # build everything
#   scons -c         # clean dist/ and build/ artefacts

import datetime
import glob
import os
import shutil
import subprocess
import sys

# -- Version -------------------------------------------------------------------
_now          = datetime.datetime.now()
BUILD_VERSION = _now.strftime("v%Y-%m-%d")

# -- Configuration -------------------------------------------------------------
APP_NAME    = "SnapshotPackCreator"
ENTRY_POINT = os.path.join("src", "main.py")

BIN_DIR  = "dist"
APP_DIR  = os.path.join(BIN_DIR, APP_NAME)          # dist/SnapshotPackCreator/
WORK_DIR = os.path.join("build", "pyinstaller-work")
SPEC_DIR = os.path.join("build")

# PDFs land here inside the bundle
DOCS_DEST = os.path.join(APP_DIR, "docs")

# build/docs/ — intermediate location for generated PDFs
_DOCS_BUILD_DIR = os.path.join("build", "docs")

# Umbrella AsciiDoc files to convert (relative to project root).
# Each entry: (adoc_path, output_stem)
ADOC_SOURCES = [
    (os.path.join("docs", "userguide",           "userguide.adoc"),            "userguide"),
    (os.path.join("docs", "developerguide",      "developerguide.adoc"),       "developerguide"),
    (os.path.join("docs", "plugin-developerguide", "plugin-developerguide.adoc"), "plugin-developerguide"),
]

# SFX installer output
SFX_EXE     = os.path.join(BIN_DIR, f"{APP_NAME}_{BUILD_VERSION}_installer.exe")
SFX_ARCHIVE = os.path.join(SPEC_DIR, "bundle.7z")

# Optional app icon
ICON_PATH = os.path.join("src", "ui", "app.ico")


# -- Helper: venv Python -------------------------------------------------------
def _python():
    venv_py = os.path.join("venv", "Scripts", "python.exe")
    if os.path.isfile(venv_py):
        return os.path.abspath(venv_py)
    return sys.executable


# -- Helper: locate 7z.exe -----------------------------------------------------
def _find_7zip():
    which = shutil.which("7z")
    if which:
        return which
    candidates = [
        r"C:\Program Files\7-Zip\7z.exe",
        r"C:\Program Files (x86)\7-Zip\7z.exe",
    ]
    for c in candidates:
        if os.path.isfile(c):
            return c
    raise FileNotFoundError(
        "7-Zip not found. Install from https://www.7-zip.org/ "
        "or add 7z.exe to PATH."
    )


# -- Helper: locate asciidoctor-pdf --------------------------------------------
def _find_asciidoctor_pdf():
    which = shutil.which("asciidoctor-pdf")
    if which:
        return which
    raise FileNotFoundError(
        "asciidoctor-pdf not found.\n"
        "Install with:  gem install asciidoctor-pdf\n"
        "Ensure the Ruby gem bin directory is on PATH."
    )


# -- Action: patch src/_version.py ---------------------------------------------
def _write_version_module(target, source, env):
    module_path = os.path.join("src", "_version.py")
    with open(module_path, "w", encoding="utf-8") as fh:
        fh.write("# Auto-generated by SConstruct — do not edit manually.\n")
        fh.write(f'BUILD_VERSION = "{BUILD_VERSION}"\n')
    print(f"Patched {module_path}  ({BUILD_VERSION})")
    with open(str(target[0]), "w", encoding="utf-8") as fh:
        fh.write(BUILD_VERSION + "\n")


# -- Action: convert all umbrella .adoc files to PDF --------------------------
def _build_docs(target, source, env):
    asciidoctor_pdf = _find_asciidoctor_pdf()
    os.makedirs(_DOCS_BUILD_DIR, exist_ok=True)

    for adoc_path, stem in ADOC_SOURCES:
        adoc_abs = os.path.abspath(adoc_path)
        if not os.path.isfile(adoc_abs):
            print(f"WARNING: AsciiDoc source not found, skipping: {adoc_abs}")
            continue
        pdf_out = os.path.abspath(os.path.join(_DOCS_BUILD_DIR, f"{stem}.pdf"))
        print(f"Converting  {adoc_abs}  ->  {pdf_out}")
        subprocess.check_call([
            asciidoctor_pdf,
            "-D", os.path.dirname(pdf_out),
            "-o", os.path.basename(pdf_out),
            adoc_abs,
        ])

    with open(str(target[0]), "w", encoding="utf-8") as fh:
        fh.write("\n".join(stem for _, stem in ADOC_SOURCES) + "\n")

    print(f"PDFs ready in  {_DOCS_BUILD_DIR}")


# -- Action: run PyInstaller ---------------------------------------------------
def _rmtree_force(path):
    """Remove a directory tree, retrying after clearing read-only flags."""
    import stat, time
    def _on_error(func, fpath, exc_info):
        try:
            os.chmod(fpath, stat.S_IWRITE)
            func(fpath)
        except Exception:
            time.sleep(0.5)
            func(fpath)
    if os.path.exists(path):
        shutil.rmtree(path, onerror=_on_error)


def _run_pyinstaller(target, source, env):
    py = _python()

    # Pre-delete the output directory so PyInstaller never hits a locked path
    out_dir = os.path.join(BIN_DIR, APP_NAME)
    if os.path.exists(out_dir):
        print(f"Removing existing dist dir: {out_dir}")
        _rmtree_force(out_dir)

    cmd = [
        py, "-m", "PyInstaller",
        "--name",     APP_NAME,
        "--windowed",
        #"--onedir",
        "--distpath", BIN_DIR,
        "--workpath", WORK_DIR,
        "--specpath", SPEC_DIR,
        "--noconfirm",
        "--paths",    "src",
    ]

    if os.path.isfile(ICON_PATH):
        cmd += ["--icon", ICON_PATH]

    # Bundle QSS stylesheet as data file
    qss_path = os.path.join("src", "ui", "style.qss")
    if os.path.isfile(qss_path):
        cmd += ["--add-data", os.path.abspath(qss_path) + os.pathsep + "ui"]

    cmd.append(str(source[0]))

    print("Running PyInstaller ...")
    print(" ".join(cmd))
    subprocess.check_call(cmd)


# -- Action: copy PDFs into the frozen bundle ----------------------------------
def _copy_docs(target, source, env):
    if os.path.exists(DOCS_DEST):
        shutil.rmtree(DOCS_DEST)
    os.makedirs(DOCS_DEST, exist_ok=True)

    for _, stem in ADOC_SOURCES:
        pdf_src = os.path.join(_DOCS_BUILD_DIR, f"{stem}.pdf")
        if os.path.isfile(pdf_src):
            dest = os.path.join(DOCS_DEST, f"{stem}.pdf")
            print(f"Copying  {pdf_src}  ->  {dest}")
            shutil.copy2(pdf_src, dest)
        else:
            print(f"WARNING: Expected PDF not found, skipping: {pdf_src}")

    with open(str(target[0]), "w", encoding="utf-8") as fh:
        fh.write("docs copied\n")


# -- Action: create console SFX installer (7zCon.sfx, no UAC) -----------------
def _create_sfx(target, source, env):
    seven_zip     = _find_7zip()
    seven_zip_dir = os.path.dirname(seven_zip)

    sfx_candidates = [
        os.path.join(seven_zip_dir, "7zCon.sfx"),
        os.path.join("tools", "7zCon.sfx"),
    ]
    sfx_module = next((p for p in sfx_candidates if os.path.isfile(p)), None)
    if sfx_module is None:
        raise FileNotFoundError(
            "7zCon.sfx (console SFX module, no UAC) not found.\n"
            "Download the '7-Zip Extra' package from https://www.7-zip.org/download.html\n"
            "and place 7zCon.sfx in one of:\n"
            + "\n".join(f"  {p}" for p in sfx_candidates)
        )

    # Pack dist/SnapshotPackCreator/ into a 7z archive
    archive_abs = os.path.abspath(SFX_ARCHIVE)
    os.makedirs(os.path.dirname(archive_abs), exist_ok=True)
    if os.path.isfile(archive_abs):
        os.remove(archive_abs)

    print(f"Creating 7z archive  ->  {archive_abs}")
    subprocess.check_call(
        [seven_zip, "a", "-t7z", "-mx=5", "-mmt=on", archive_abs, APP_NAME,
         "-xr!.copied"],
        cwd=os.path.abspath(BIN_DIR),
    )

    # Concatenate SFX module + archive -> installer exe
    sfx_exe = str(target[0])
    os.makedirs(os.path.dirname(sfx_exe) or ".", exist_ok=True)
    print(f"Building SFX  ->  {sfx_exe}")
    with open(sfx_exe, "wb") as out:
        for part in (sfx_module, archive_abs):
            with open(part, "rb") as inp:
                shutil.copyfileobj(inp, out)

    print(f"\nInstaller ready:  {sfx_exe}")
    print(f"  Extract to current dir  : {os.path.basename(sfx_exe)}")
    print(f"  Extract to target path  : {os.path.basename(sfx_exe)} -o\"C:\\Target\"")


# -- SCons environment ---------------------------------------------------------
env = Environment(ENV=os.environ)  # type: ignore


# -- Target 0: patch _version.py -----------------------------------------------
_version_sentinel = os.path.join("build", "_version.ok")

patch_version = env.Command(
    target = _version_sentinel,
    source = [],
    action = _write_version_module,
)
env.AlwaysBuild(patch_version)


# -- Target 1: convert AsciiDoc files to PDF -----------------------------------
_docs_sentinel = os.path.join(_DOCS_BUILD_DIR, ".docs.ok")

build_docs = env.Command(
    target = _docs_sentinel,
    source = [adoc for adoc, _ in ADOC_SOURCES],
    action = _build_docs,
)
env.AlwaysBuild(build_docs)


# -- Target 2: freeze with PyInstaller -----------------------------------------
_exe_sentinel = os.path.join(APP_DIR, f"{APP_NAME}.exe")

pyinstaller_build = env.Command(
    target = _exe_sentinel,
    source = [ENTRY_POINT, patch_version],
    action = _run_pyinstaller,
)
env.AlwaysBuild(pyinstaller_build)


# -- Target 3: copy PDFs into frozen bundle ------------------------------------
_docs_bundle_sentinel = os.path.join(DOCS_DEST, ".copied")

copy_docs = env.Command(
    target = _docs_bundle_sentinel,
    source = [pyinstaller_build, build_docs],
    action = _copy_docs,
)


# -- Target 4: create SFX installer -------------------------------------------
create_sfx = env.Command(
    target = SFX_EXE,
    source = copy_docs,
    action = _create_sfx,
)


# -- Default + clean -----------------------------------------------------------
env.Default(create_sfx)

env.Clean(create_sfx, [BIN_DIR, WORK_DIR, SPEC_DIR])
