# SConstruct — Build script for Snapshot Pack Creator
#
# Targets (in order, repeated for each torch variant):
#   1. Patch src/_version.py with the current build timestamp
#   2. Convert umbrella AsciiDoc files to PDF  (requires asciidoctor-pdf)
#   3. Install the correct torch wheel into the venv
#   4. Freeze the application with PyInstaller  (one-directory bundle per variant)
#   5. Copy PDFs into the frozen bundle
#   6. Pack everything into a console SFX installer  (7zCon.sfx, no UAC)
#
# Torch variants
# --------------
#   cpu   — CPU-only (any machine)
#   cu121 — CUDA 12.1 (most NVIDIA GPUs)
#   cu128 — CUDA 12.8 (RTX 5080 / Blackwell sm_120)
#
# Prerequisites
# -------------
#   1. Run cli.bat to create the venv and install pip requirements.
#   2. Install asciidoctor-pdf (Ruby gem):
#        gem install asciidoctor-pdf
#   3. Install 7-Zip Extra and place 7zCon.sfx beside 7z.exe or in tools/.
#        https://www.7-zip.org/download.html  ("7-Zip Extra")
#   4. Install PyInstaller into the venv:
#        venv\Scripts\pip install pyinstaller
#
# Usage
# -----
#   scons                # build all three torch variants
#   scons torch=cpu      # build CPU-only variant only
#   scons torch=cu121    # build CUDA 12.1 variant only
#   scons torch=cu128    # build CUDA 12.8 variant only
#   scons -c             # clean dist/ and build/ artefacts

import datetime
import glob
import os
import shutil
import subprocess
import sys

# -- Version -------------------------------------------------------------------
_now          = datetime.datetime.now()
BUILD_VERSION = _now.strftime("v%Y-%m-%d")

# -- Torch variants ------------------------------------------------------------
TORCH_VARIANTS = {
    "cpu":   "https://download.pytorch.org/whl/cpu",
    "cu121": "https://download.pytorch.org/whl/cu121",
    "cu128": "https://download.pytorch.org/whl/cu128",
}

# scons torch=cpu|cu121|cu128  selects a single variant; default builds all.
_torch_arg = ARGUMENTS.get("torch", "all")  # type: ignore[name-defined]
if _torch_arg == "all":
    _build_variants = list(TORCH_VARIANTS.keys())
elif _torch_arg in TORCH_VARIANTS:
    _build_variants = [_torch_arg]
else:
    print(f"ERROR: torch={_torch_arg!r} unknown. Valid choices: {', '.join(TORCH_VARIANTS)}")
    Exit(1)  # type: ignore[name-defined]

# -- Configuration -------------------------------------------------------------
APP_NAME    = "SnapshotPackCreator"
ENTRY_POINT = os.path.join("src", "main.py")

BIN_DIR  = "dist"
WORK_DIR = os.path.join("build", "pyinstaller-work")
SPEC_DIR = os.path.join("build")

# build/docs/ — intermediate location for generated PDFs
_DOCS_BUILD_DIR = os.path.join("build", "docs")

# Umbrella AsciiDoc files to convert (relative to project root).
# Each entry: (adoc_path, output_stem)
ADOC_SOURCES = [
    (os.path.join("docs", "userguide",           "userguide.adoc"),            "userguide"),
    (os.path.join("docs", "developerguide",      "developerguide.adoc"),       "developerguide"),
    (os.path.join("docs", "plugin-developerguide", "plugin-developerguide.adoc"), "plugin-developerguide"),
]

# Optional app icon
ICON_PATH = os.path.join("src", "ui", "app.ico")


# -- Helper: venv Python -------------------------------------------------------
def _python():
    venv_py = os.path.join("venv", "Scripts", "python.exe")
    if os.path.isfile(venv_py):
        return os.path.abspath(venv_py)
    return sys.executable


# -- Helper: locate 7z.exe -----------------------------------------------------
def _find_7zip():
    which = shutil.which("7z")
    if which:
        return which
    candidates = [
        r"C:\Program Files\7-Zip\7z.exe",
        r"C:\Program Files (x86)\7-Zip\7z.exe",
    ]
    for c in candidates:
        if os.path.isfile(c):
            return c
    raise FileNotFoundError(
        "7-Zip not found. Install from https://www.7-zip.org/ "
        "or add 7z.exe to PATH."
    )


# -- Helper: locate asciidoctor-pdf --------------------------------------------
def _find_asciidoctor_pdf():
    which = shutil.which("asciidoctor-pdf")
    if which:
        return which
    raise FileNotFoundError(
        "asciidoctor-pdf not found.\n"
        "Install with:  gem install asciidoctor-pdf\n"
        "Ensure the Ruby gem bin directory is on PATH."
    )


# -- Action: patch src/_version.py ---------------------------------------------
def _write_version_module(target, source, env):
    module_path = os.path.join("src", "_version.py")
    with open(module_path, "w", encoding="utf-8") as fh:
        fh.write("# Auto-generated by SConstruct — do not edit manually.\n")
        fh.write(f'BUILD_VERSION = "{BUILD_VERSION}"\n')
    print(f"Patched {module_path}  ({BUILD_VERSION})")
    with open(str(target[0]), "w", encoding="utf-8") as fh:
        fh.write(BUILD_VERSION + "\n")


# -- Action: convert all umbrella .adoc files to PDF --------------------------
def _build_docs(target, source, env):
    asciidoctor_pdf = _find_asciidoctor_pdf()
    os.makedirs(_DOCS_BUILD_DIR, exist_ok=True)

    for adoc_path, stem in ADOC_SOURCES:
        adoc_abs = os.path.abspath(adoc_path)
        if not os.path.isfile(adoc_abs):
            print(f"WARNING: AsciiDoc source not found, skipping: {adoc_abs}")
            continue
        pdf_out = os.path.abspath(os.path.join(_DOCS_BUILD_DIR, f"{stem}.pdf"))
        print(f"Converting  {adoc_abs}  ->  {pdf_out}")
        subprocess.check_call([
            asciidoctor_pdf,
            "-D", os.path.dirname(pdf_out),
            "-o", os.path.basename(pdf_out),
            adoc_abs,
        ])

    with open(str(target[0]), "w", encoding="utf-8") as fh:
        fh.write("\n".join(stem for _, stem in ADOC_SOURCES) + "\n")

    print(f"PDFs ready in  {_DOCS_BUILD_DIR}")


# -- Action: run PyInstaller ---------------------------------------------------
def _rmtree_force(path):
    """Remove a directory tree, retrying after clearing read-only flags."""
    import stat, time
    def _on_error(func, fpath, exc_info):
        try:
            os.chmod(fpath, stat.S_IWRITE)
            func(fpath)
        except Exception:
            time.sleep(0.5)
            func(fpath)
    if os.path.exists(path):
        shutil.rmtree(path, onerror=_on_error)


def _run_pyinstaller(target, source, env):
    py      = _python()
    variant = env["TORCH_VARIANT"]
    app_dir = os.path.join(BIN_DIR, f"{APP_NAME}_{variant}")

    if os.path.exists(app_dir):
        print(f"Removing existing dist dir: {app_dir}")
        _rmtree_force(app_dir)

    cmd = [
        py, "-m", "PyInstaller",
        "--name",     f"{APP_NAME}_{variant}",
        "--windowed",
        "--distpath", BIN_DIR,
        "--workpath", os.path.join(WORK_DIR, variant),
        "--specpath", SPEC_DIR,
        "--noconfirm",
        "--paths",    "src",
    ]

    if os.path.isfile(ICON_PATH):
        cmd += ["--icon", ICON_PATH]

    qss_path = os.path.join("src", "ui", "style.qss")
    if os.path.isfile(qss_path):
        cmd += ["--add-data", os.path.abspath(qss_path) + os.pathsep + "ui"]

    prompts_path = os.path.join("src", "prompts.json")
    if os.path.isfile(prompts_path):
        cmd += ["--add-data", os.path.abspath(prompts_path) + os.pathsep + "."]

    city_events_templates_path = os.path.join("src", "city_events_templates.json")
    if os.path.isfile(city_events_templates_path):
        cmd += ["--add-data", os.path.abspath(city_events_templates_path) + os.pathsep + "."]

    cmd.append(str(source[0]))

    print(f"Running PyInstaller [{variant}] ...")
    print(" ".join(cmd))
    subprocess.check_call(cmd)


# -- Action: copy PDFs into the frozen bundle ----------------------------------
def _copy_docs(target, source, env):
    variant   = env["TORCH_VARIANT"]
    docs_dest = os.path.join(BIN_DIR, f"{APP_NAME}_{variant}", "docs")

    if os.path.exists(docs_dest):
        shutil.rmtree(docs_dest)
    os.makedirs(docs_dest, exist_ok=True)

    for _, stem in ADOC_SOURCES:
        pdf_src = os.path.join(_DOCS_BUILD_DIR, f"{stem}.pdf")
        if os.path.isfile(pdf_src):
            dest = os.path.join(docs_dest, f"{stem}.pdf")
            print(f"Copying  {pdf_src}  ->  {dest}")
            shutil.copy2(pdf_src, dest)
        else:
            print(f"WARNING: Expected PDF not found, skipping: {pdf_src}")

    with open(str(target[0]), "w", encoding="utf-8") as fh:
        fh.write("docs copied\n")


# -- Action: install torch variant into the venv --------------------------------
def _install_torch(target, source, env):
    py          = _python()
    variant     = env["TORCH_VARIANT"]
    index_url   = TORCH_VARIANTS[variant]
    print(f"Installing torch [{variant}] from {index_url} ...")
    subprocess.check_call([
        py, "-m", "pip", "install", "torch", "torchvision",
        "--index-url", index_url,
    ])
    with open(str(target[0]), "w", encoding="utf-8") as fh:
        fh.write(index_url + "\n")


# -- Action: create console SFX installer (7zCon.sfx, no UAC) -----------------
def _create_sfx(target, source, env):
    seven_zip     = _find_7zip()
    seven_zip_dir = os.path.dirname(seven_zip)
    variant       = env["TORCH_VARIANT"]
    app_bundle    = f"{APP_NAME}_{variant}"

    sfx_candidates = [
        os.path.join(seven_zip_dir, "7zCon.sfx"),
        os.path.join("tools", "7zCon.sfx"),
    ]
    sfx_module = next((p for p in sfx_candidates if os.path.isfile(p)), None)
    if sfx_module is None:
        raise FileNotFoundError(
            "7zCon.sfx (console SFX module, no UAC) not found.\n"
            "Download the '7-Zip Extra' package from https://www.7-zip.org/download.html\n"
            "and place 7zCon.sfx in one of:\n"
            + "\n".join(f"  {p}" for p in sfx_candidates)
        )

    archive_abs = os.path.abspath(
        os.path.join(SPEC_DIR, f"bundle_{variant}.7z")
    )
    os.makedirs(os.path.dirname(archive_abs), exist_ok=True)
    if os.path.isfile(archive_abs):
        os.remove(archive_abs)

    print(f"Creating 7z archive [{variant}]  ->  {archive_abs}")
    subprocess.check_call(
        [seven_zip, "a", "-t7z", "-mx=5", "-mmt=on", archive_abs, app_bundle,
         "-xr!.copied"],
        cwd=os.path.abspath(BIN_DIR),
    )

    sfx_exe = str(target[0])
    os.makedirs(os.path.dirname(sfx_exe) or ".", exist_ok=True)
    print(f"Building SFX [{variant}]  ->  {sfx_exe}")
    with open(sfx_exe, "wb") as out:
        for part in (sfx_module, archive_abs):
            with open(part, "rb") as inp:
                shutil.copyfileobj(inp, out)

    print(f"\nInstaller ready:  {sfx_exe}")
    print(f"  Extract to current dir  : {os.path.basename(sfx_exe)}")
    print(f"  Extract to target path  : {os.path.basename(sfx_exe)} -o\"C:\\Target\"")


# -- SCons environment ---------------------------------------------------------
env = Environment(ENV=os.environ)  # type: ignore


# -- Target 0: patch _version.py  (shared, run once) --------------------------
_version_sentinel = os.path.join("build", "_version.ok")

patch_version = env.Command(
    target = _version_sentinel,
    source = [],
    action = _write_version_module,
)
env.AlwaysBuild(patch_version)


# -- Target 1: convert AsciiDoc files to PDF  (shared, run once) --------------
_docs_sentinel = os.path.join(_DOCS_BUILD_DIR, ".docs.ok")

build_docs = env.Command(
    target = _docs_sentinel,
    source = [adoc for adoc, _ in ADOC_SOURCES],
    action = _build_docs,
)
env.AlwaysBuild(build_docs)


# -- Targets 2-5: per-variant  (install torch → freeze → copy docs → sfx) ----
all_sfx = []
_prev_install = None   # enforce sequential torch installs

for _variant in _build_variants:
    _venv      = env.Clone()
    _venv["TORCH_VARIANT"] = _variant

    _app_dir     = os.path.join(BIN_DIR, f"{APP_NAME}_{_variant}")
    _exe_sentinel = os.path.join(_app_dir, f"{APP_NAME}_{_variant}.exe")
    _docs_bundle  = os.path.join(_app_dir, "docs", ".copied")
    _sfx_exe      = os.path.join(BIN_DIR, f"{APP_NAME}_{BUILD_VERSION}_{_variant}_installer.exe")
    _torch_stamp  = os.path.join("build", f".torch_{_variant}.ok")

    # Step 2: install torch variant
    install_torch = _venv.Command(
        target = _torch_stamp,
        source = [],
        action = _install_torch,
    )
    _venv.AlwaysBuild(install_torch)
    _venv.Depends(install_torch, patch_version)
    if _prev_install is not None:
        # Don't overlap torch installs — wait for the previous variant to finish
        _venv.Depends(install_torch, _prev_install)
    _prev_install = install_torch

    # Step 3: freeze with PyInstaller
    pyinstaller_build = _venv.Command(
        target = _exe_sentinel,
        source = [ENTRY_POINT, install_torch],
        action = _run_pyinstaller,
    )
    _venv.AlwaysBuild(pyinstaller_build)

    # Step 4: copy PDFs into frozen bundle
    copy_docs_node = _venv.Command(
        target = _docs_bundle,
        source = [pyinstaller_build, build_docs],
        action = _copy_docs,
    )

    # Step 5: create SFX installer
    sfx_node = _venv.Command(
        target = _sfx_exe,
        source = copy_docs_node,
        action = _create_sfx,
    )
    all_sfx.append(sfx_node)


# -- Plugins: packaged as separate SFX installers, never bundled into the app -
#
# plugins/ is intentionally excluded from the PyInstaller bundle above (no
# --add-data entry). Instead each plugin folder under plugins/ gets its own
# torch-independent SFX installer that the user extracts into plugins\.

PLUGINS_DIR = "plugins"


def _discover_plugins():
    if not os.path.isdir(PLUGINS_DIR):
        return []
    names = []
    for entry in sorted(os.listdir(PLUGINS_DIR)):
        entry_path = os.path.join(PLUGINS_DIR, entry)
        if os.path.isdir(entry_path) and os.path.isfile(os.path.join(entry_path, "__init__.py")):
            names.append(entry)
    return names


def _create_plugin_sfx(target, source, env):
    seven_zip     = _find_7zip()
    seven_zip_dir = os.path.dirname(seven_zip)
    plugin_name   = env["PLUGIN_NAME"]

    sfx_candidates = [
        os.path.join(seven_zip_dir, "7zCon.sfx"),
        os.path.join("tools", "7zCon.sfx"),
    ]
    sfx_module = next((p for p in sfx_candidates if os.path.isfile(p)), None)
    if sfx_module is None:
        raise FileNotFoundError(
            "7zCon.sfx (console SFX module, no UAC) not found.\n"
            "Download the '7-Zip Extra' package from https://www.7-zip.org/download.html\n"
            "and place 7zCon.sfx in one of:\n"
            + "\n".join(f"  {p}" for p in sfx_candidates)
        )

    archive_abs = os.path.abspath(os.path.join(SPEC_DIR, f"plugin_{plugin_name}.7z"))
    os.makedirs(os.path.dirname(archive_abs), exist_ok=True)
    if os.path.isfile(archive_abs):
        os.remove(archive_abs)

    print(f"Creating 7z archive for plugin [{plugin_name}]  ->  {archive_abs}")
    subprocess.check_call(
        [seven_zip, "a", "-t7z", "-mx=5", "-mmt=on", archive_abs, plugin_name,
         "-xr!__pycache__", "-xr!*.pyc"],
        cwd=os.path.abspath(PLUGINS_DIR),
    )

    sfx_exe = str(target[0])
    os.makedirs(os.path.dirname(sfx_exe) or ".", exist_ok=True)
    print(f"Building plugin SFX [{plugin_name}]  ->  {sfx_exe}")
    with open(sfx_exe, "wb") as out:
        for part in (sfx_module, archive_abs):
            with open(part, "rb") as inp:
                shutil.copyfileobj(inp, out)

    print(f"\nPlugin installer ready:  {sfx_exe}")
    print(f"  Extract into plugins\\ : {os.path.basename(sfx_exe)} -o\"plugins\"")


all_plugin_sfx = []
for _plugin_name in _discover_plugins():
    _plugin_sfx_exe = os.path.join(
        BIN_DIR, f"{_plugin_name}_{BUILD_VERSION}_installer.exe"
    )
    _plugin_env = env.Clone()
    _plugin_env["PLUGIN_NAME"] = _plugin_name
    _plugin_sources = glob.glob(os.path.join(PLUGINS_DIR, _plugin_name, "**", "*"), recursive=True)
    plugin_sfx_node = _plugin_env.Command(
        target = _plugin_sfx_exe,
        source = _plugin_sources,
        action = _create_plugin_sfx,
    )
    all_plugin_sfx.append(plugin_sfx_node)


# -- Default + clean -----------------------------------------------------------
env.Default(all_sfx)
env.Default(all_plugin_sfx)

_clean_paths = [BIN_DIR, WORK_DIR, SPEC_DIR]
env.Clean(all_sfx, _clean_paths)
env.Clean(all_plugin_sfx, _clean_paths)


# -- Post-build: restore venv torch for the dev machine -----------------------
def _restore_dev_torch(target, source, env):
    """Re-install the machine-correct torch after all variant builds finish.

    After building multiple variants the venv is left with the last variant's
    torch.  This step re-detects the GPU (same logic as cli.bat) and puts the
    right wheel back so the dev environment still works.
    """
    import subprocess as _sp
    py = _python()

    # Detect GPU via wmic (Windows only; skip gracefully on other platforms).
    gpu_name = ""
    try:
        out = _sp.check_output(
            ["wmic", "path", "win32_VideoController", "get", "name"],
            stderr=_sp.DEVNULL, text=True,
        )
        lines = [l.strip() for l in out.splitlines() if l.strip() and l.strip().lower() != "name"]
        if lines:
            gpu_name = lines[0]
    except Exception:
        pass

    if "RTX 5080" in gpu_name:
        index_url = TORCH_VARIANTS["cu128"]
        label = "cu128 (RTX 5080)"
    elif "NVIDIA" in gpu_name:
        index_url = TORCH_VARIANTS["cu121"]
        label = f"cu121 ({gpu_name.strip()})"
    else:
        index_url = TORCH_VARIANTS["cpu"]
        label = "cpu-only"

    print(f"\nRestoring dev-venv torch: {label}  ({index_url})")
    _sp.check_call([py, "-m", "pip", "install", "torch", "torchvision",
                    "--index-url", index_url])
    with open(str(target[0]), "w", encoding="utf-8") as fh:
        fh.write(label + "\n")
    print("Dev-venv torch restored.")


_restore_stamp = os.path.join("build", ".torch_dev_restored.ok")
restore_torch = env.Command(
    target = _restore_stamp,
    source = all_sfx,
    action = _restore_dev_torch,
)
env.AlwaysBuild(restore_torch)
env.Default(restore_torch)
