"""Tests for src/_version.py — version module generated by SConstruct."""

import importlib
import sys
import os

import pytest

# Ensure src/ is on the path (conftest.py does this globally, but be explicit)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))


def test_version_module_is_importable():
    import _version  # noqa: F401


def test_build_version_is_string():
    import _version
    assert isinstance(_version.BUILD_VERSION, str)


def test_build_version_not_empty():
    import _version
    assert _version.BUILD_VERSION.strip() != ""


def test_build_version_starts_with_v():
    import _version
    # SConstruct always writes 'vYYYY-MM-DD'; placeholder is 'v0.0.0-dev'
    assert _version.BUILD_VERSION.startswith("v")
